changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking
    - title: New Features
      labels:
        - new-feature
    - title: Bug Fixes
      labels:
        - bug-fix
    - title: Miscellaneous Changes
      labels:
        - "*"
