[package]
name = "shai"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "4.1"
directories = "4.0"
is-terminal = "0.4"
ureq = { version = "2.6", features = ["tls", "gzip", "brotli", "native-certs", "json"] }
