name: Release
on:
  workflow_run:
    workflows: Test
    types: completed
    branches: main
jobs:
  is-release:
    runs-on: ubuntu-latest
    outputs:
      result: ${{ steps.is-release.outputs.result }}
    steps:
      - name: Is release?
        id: is-release
        env:
          REF_TYPE: ${{ github.ref_type }}
          REF_NAME: ${{ github.ref_name }}
        shell: python
        run: |
          import os
          import re

          is_tag = os.environ['REF_TYPE'] == 'tag'
          is_version_number = re.match(
              r'^v\d+\.\d+\.\d+$',
              os.environ['REF_NAME']
          )
          is_version_tag = is_tag and is_version_number
          result = 'true' if is_version_tag else 'false'

          with open(os.environ['GITHUB_OUTPUT'], 'w') as f:
              f.write('result=' + result)
