name: Test
on: 
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches: main
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Typecheck
        run: cargo check
      - name: Clippy
        run: cargo clippy
  test:
    needs: lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Cache Rust
        uses: Swatinem/rust-cache@v2
      - name: Run tests
        run: cargo test
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
